/// <reference types="vitest/config" />
import { fileURLToPath, URL } from 'node:url'
import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'
import { VitePWA } from 'vite-plugin-pwa'

const LIGHT_BACKGROUND = '#F3F4F8'

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      // The update is applied only when the user accepts it (src/pwa/useServiceWorker.ts).
      registerType: 'prompt',
      // Registered from React through `virtual:pwa-register` (no auto-injected script).
      injectRegister: false,
      // Icons are static files generated by `npm run generate-pwa-assets` (pwa-assets.config.ts).
      // They are already precached by the glob below (the plugin itself adds manifest.webmanifest).
      includeManifestIcons: false,
      manifest: {
        id: '/',
        name: 'Erasmus Help',
        short_name: 'Erasmus Help',
        description:
          'Apoio a estudantes Erasmus: tradução por voz, conversa frente a frente, prática de idiomas e meteorologia.',
        lang: 'pt-PT',
        dir: 'ltr',
        start_url: '/',
        scope: '/',
        display: 'standalone',
        orientation: 'portrait',
        background_color: LIGHT_BACKGROUND,
        theme_color: LIGHT_BACKGROUND,
        categories: ['education', 'travel', 'utilities'],
        icons: [
          { src: '/brand/pwa-64x64.png', sizes: '64x64', type: 'image/png', purpose: 'any' },
          { src: '/brand/pwa-192x192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: '/brand/pwa-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          { src: '/brand/maskable-icon-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
      workbox: {
        // App shell: everything Vite emits + public icons/fonts. Lazy route chunks included → full offline shell.
        globPatterns: ['**/*.{js,css,html,svg,png,ico,woff2}'],
        // UI languages (pt/en/pl) and conversation languages only need latin + latin-ext glyphs; the other
        // font subsets still load on demand online (unicode-range) and fall back to system fonts offline.
        globIgnores: ['**/*-{cyrillic,cyrillic-ext,greek,greek-ext,vietnamese}-*.woff2'],
        // SPA navigations (any route, incl. ?mode=…) get the precached shell while offline…
        navigateFallback: '/index.html',
        // …except API-like paths and direct file URLs (/sw.js, /brand/x.png, /manifest.webmanifest).
        navigateFallbackDenylist: [/^\/api\//, /\/[^/?]+\.[^/?]+(?:\?.*)?$/],
        cleanupOutdatedCaches: true,
        // First visit: take control immediately (runtime caches + offline work without a reload).
        // Updates still wait for the user because skipWaiting stays off in 'prompt' mode.
        clientsClaim: true,
        disableDevLogs: true,
        // Opens the conversation when a chat notification is clicked (public/sw-notifications.js).
        importScripts: ['/sw-notifications.js'],
        // Only these third-party GETs are cached. Our backend (VITE_API_BASE_URL: translation/AI) has
        // NO route on purpose: the service worker never intercepts it, so private responses are never cached.
        runtimeCaching: [
          {
            // Weather must be fresh; fall back to a ≤1 h old copy when the network is slow/offline.
            urlPattern: /^https:\/\/api\.open-meteo\.com\/.*/i,
            handler: 'NetworkFirst',
            options: {
              cacheName: 'eh-weather',
              networkTimeoutSeconds: 4,
              expiration: { maxEntries: 16, maxAgeSeconds: 60 * 60 },
              cacheableResponse: { statuses: [200] },
            },
          },
          {
            // City search results barely change: answer from cache, refresh in the background.
            urlPattern: /^https:\/\/geocoding-api\.open-meteo\.com\/.*/i,
            handler: 'StaleWhileRevalidate',
            options: {
              cacheName: 'eh-geocoding',
              expiration: { maxEntries: 60, maxAgeSeconds: 24 * 60 * 60 },
              cacheableResponse: { statuses: [200] },
            },
          },
        ],
      },
      // Never register a SW during `npm run dev` (stale-cache pitfalls); test with `npm run build && npm run preview`.
      devOptions: { enabled: false },
    }),
  ],
  resolve: {
    alias: { '@': fileURLToPath(new URL('./src', import.meta.url)) },
  },
  test: {
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.ts'],
    include: ['src/**/*.test.{ts,tsx}'],
  },
})
